### ISSUE TITLE
打包成exe檔

### ISSUE THREAD

**Issue by Dylan-Hong** [Dylan-Hong/Stock-Crawler#5]
- [ ] 確認Mac跟window建立後，是否能在另一個環境執行
- [ ] 釐清檔案輸出或讀取的路徑設定，並確認正斜線與反斜線問題
- [ ] 是否有機會能縮小打包的檔案大小，例如不要import整個完整模組

**Comment by wuweihsun** [comment]
好喔

**Comment by Dylan-Hong** [comment]
感覺這週可以做打包+人機這兩件事情

**Comment by wuweihsun** [comment]
更正，人機可能沒這麼簡單😂
